install:
  - choco install yarn
  - refreshenv
  - yarn install

cache:
 - "%LOCALAPPDATA%/Yarn"
 - node_modules -> package.json

build: off
shallow_clone: true
clone_depth: 1
skip_branch_with_pr: true

test_script:
  - node --version
  - yarn test
